[AQUANAUT_HELMET]
DAMAGE_ENABLED = true
DURABILITY = 600
EFFECT_TIME_WITH_EFFICIENCY_0 = 60
EFFECT_TIME_WITH_EFFICIENCY_1 = 120
EFFECT_TIME_WITH_EFFICIENCY_2 = 180
EFFECT_TIME_WITH_EFFICIENCY_3 = 240
EFFECT_TIME_WITH_EFFICIENCY_4 = 300
EFFECT_TIME_WITH_EFFICIENCY_5 = 360
[BUNNY_EARS]
DAMAGE_ENABLED = true
DURABILITY = 450
[CHOPPING_HAT]
DAMAGE_ENABLED = true
DURABILITY = 300
SPEED_WITH_EFFICIENCY_0 = 20
SPEED_WITH_EFFICIENCY_1 = 40
SPEED_WITH_EFFICIENCY_2 = 60
SPEED_WITH_EFFICIENCY_3 = 80
SPEED_WITH_EFFICIENCY_4 = 100
SPEED_WITH_EFFICIENCY_5 = 150
[ENDER_HELMET]
DAMAGE_ENABLED = true
DURABILITY = 80
INTERDIMENSIONAL_ENABLED = true
[HALO]
DAMAGE_ENABLED = true
DURABILITY = 600
[LUCKY_HAT]
DAMAGE_ENABLED = true
DURABILITY = 300
UNLUCK_ENABLED = true
[MINING_HAT]
DAMAGE_ENABLED = true
DURABILITY = 450
NIGHT_VISION_ENABLED = true
MAKE_PIGLINS_NEUTRAL_ENABLED = true
SPEED_WITH_EFFICIENCY_0 = 20
SPEED_WITH_EFFICIENCY_1 = 40
SPEED_WITH_EFFICIENCY_2 = 60
SPEED_WITH_EFFICIENCY_3 = 80
SPEED_WITH_EFFICIENCY_4 = 100
SPEED_WITH_EFFICIENCY_5 = 150
[MUSHROOM_HAT]
DAMAGE_ENABLED = true
DURABILITY = 80
EAT_INTERVAL = 60
[POSTMAN_HAT]
DAMAGE_ENABLED = true
DURABILITY = 600
HUNGER_ENABLED = true
[SHULKER_HELMET]
DAMAGE_ENABLED = true
DURABILITY = 600
[STOCKING_CAP]
DAMAGE_ENABLED = true
DURABILITY = 600
[STRAW_HAT]
DAMAGE_ENABLED = true
DURABILITY = 300
SPEED_WITH_EFFICIENCY_0 = 20
SPEED_WITH_EFFICIENCY_1 = 40
SPEED_WITH_EFFICIENCY_2 = 60
SPEED_WITH_EFFICIENCY_3 = 80
SPEED_WITH_EFFICIENCY_4 = 100
SPEED_WITH_EFFICIENCY_5 = 150
[WING_HELMET]
DAMAGE_ENABLED = true
DURABILITY = 600
LEVITATION_ENABLED = true
